# Generated by Django 3.2.13 on 2022-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220705_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='time',
            new_name='timestamp',
        ),
    ]
